### ISSUE TITLE
Captcha::create(null, true) 报错

### ISSUE THREAD

**Issue by gitee1** [yzh52521/think-captcha#1]
yzh52521\captcha\Captcha类中，create方法的返回值约定了Response，但是参数中$api = true 时，返回值为array，会报错。

**Comment by yuanzhihai** [comment]
修复了 试试

**Comment by gitee1** [comment]
create方法中，$generator = $this->generate()这一行应该把$api当参数传过去吧，现在没有传。

**Comment by yuanzhihai** [comment]
可以了看看

**Comment by gitee1** [comment]
> 可以了看看

好的，😊

**Comment by gitee1** [comment]
> 可以了看看

好的，😊
